"""add demo_mode to users

Revision ID: b15a1a5151c1
Revises: 6936c20009b1
Create Date: 2026-06-08 22:56:08.624201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b15a1a5151c1'
down_revision: Union[str, None] = '6936c20009b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('demo_mode', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'demo_mode')
    # ### end Alembic commands ###
